package io.github.mribby.papermario.item;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.entity.ai.attributes.AttributeModifier;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;

import static io.github.mribby.papermario.Game.*;

public class PaperMarioItems {

    public static final ItemArmor.ArmorMaterial STONE_CAP_MATERIAL = EnumHelper.addArmorMaterial("STONE_CAP", 2, new int[]{20, 0, 0, 0}, 0);
    public static final AttributeModifier STONE_CAP_MODIFIER = new AttributeModifier("Stone cap speed reduction", -1.0D, 2).setSaved(false);;

    /// PAPER MARIO ///

    public static final Item snowman_doll = new ItemSnowmanDoll();
    public static final Item pebble = new ItemDamageThrown(1, PM).setUnlocalizedName("papermario.pebble").setTextureName("papermario:pebble");
    public static final Item dusty_hammer = new ItemDamagePhysical(1, PM).setUnlocalizedName("papermario.dustyHammer").setTextureName("papermario:dusty_hammer");
    public static final Item stone_cap = new ItemStoneCap();
    public static final Item apple = new PaperMarioItemFood(5, 0, PM).setUnlocalizedName("papermario.apple").setTextureName("papermario:apple");
    public static final Item repel_gel = new ItemRepelGel();
    public static final Item fright_jar = new ItemFrightJar();
    public static final Item super_soda = new ItemSuperSoda();
    public static final Item lemon = new PaperMarioItemFood(1, 2, PM).setUnlocalizedName("papermario.lemon").setTextureName("papermario:lemon");
    public static final Item lime = new PaperMarioItemFood(0, 3, PM).setUnlocalizedName("papermario.lime").setTextureName("papermario:lime");
    public static final Item blue_berry = new PaperMarioItemFood(0, 5, PM).setUnlocalizedName("papermario.blueBerry").setTextureName("papermario:blue_berry");
    public static final Item red_berry = new PaperMarioItemFood(5, 0, PM).setUnlocalizedName("papermario.redBerry").setTextureName("papermario:red_berry");
    public static final Item yellow_berry = new PaperMarioItemFood(3, 3, PM).setUnlocalizedName("papermario.yellowBerry").setTextureName("papermario:yellow_berry");
    public static final Item bubble_berry = new PaperMarioItemFood(0, 5, PM).setUnlocalizedName("papermario.bubbleBerry").setTextureName("papermario:bubble_berry");
    public static final Item goomnut = new PaperMarioItemFood(0, 3, PM).setUnlocalizedName("papermario.goomnut").setTextureName("papermario:goomnut");
    public static final Item koopa_leaf = new PaperMarioItemFood(0, 3, PM, PMTTYD, SPM).setUnlocalizedName("papermario.koopaLeaf").setTextureName("papermario:koopa_leaf");
    public static final Item dried_pasta = new PaperMarioItemFood(3, 2, PM).setUnlocalizedName("papermario.driedPasta").setTextureName("papermario:dried_pasta");
    public static final Item dried_fruit = new PaperMarioItemFood(15, 0, PM).setUnlocalizedName("papermario.driedFruit").setTextureName("papermario:dried_fruit");
    public static final Item strange_leaf = new PaperMarioItemFood(0, 5, PM).setUnlocalizedName("papermario.strangeLeaf").setTextureName("papermario:strange_leaf");
    public static final Item egg = new PaperMarioItemFood(5, 0, PM).setUnlocalizedName("papermario.egg").setTextureName("papermario:egg");
    public static final Item melon = new PaperMarioItemFood(15, 0, PM).setUnlocalizedName("papermario.melon").setTextureName("papermario:melon");
    public static final Item stinky_herb = new PaperMarioItemFood(0, 5, PM).setUnlocalizedName("papermario.stinkyHerb").setTextureName("papermario:stinky_herb");
    public static final Item iced_potato = new PaperMarioItemFood(5, 0, PM).setUnlocalizedName("papermario.icedPotato").setTextureName("papermario:iced_potato");
    public static final Item apple_pie = new PaperMarioItemFood(5, 15, PM).setUnlocalizedName("papermario.applePie").setTextureName("papermario:apple_pie");
    public static final Item fried_shroom = new PaperMarioItemFood(6, 2, PM).setUnlocalizedName("papermario.friedShroom").setTextureName("papermario:fried_shroom");
    public static final Item hot_shroom = new PaperMarioItemFood(15, 5, PM).setUnlocalizedName("papermario.hotShroom").setTextureName("papermario:hot_shroom");
    public static final Item sweet_shroom = new PaperMarioItemFood(30, 20, PM).setUnlocalizedName("papermario.sweetShroom").setTextureName("papermario:sweet_shroom");
    public static final Item yummy_meal = new PaperMarioItemFood(20, 20, PM).setUnlocalizedName("papermario.yummyMeal").setTextureName("papermario:yummy_meal");
    public static final Item healthy_juice = new ItemDrink(40, PM).setUnlocalizedName("papermario.healthyJuice").setTextureName("papermario:healthy_juice");
    public static final Item bland_meal = new PaperMarioItemFood(10, 10, PM).setUnlocalizedName("papermario.blandMeal").setTextureName("papermario:bland_meal");
    public static final Item deluxe_feast = new PaperMarioItemFood(40, 40, PM).setUnlocalizedName("papermario.deluxeFeast").setTextureName("papermario:deluxe_feast");
    public static final Item special_shake = new ItemDrink(20, PM).setUnlocalizedName("papermario.specialShake").setTextureName("papermario:special_shake");
    public static final Item big_cookie = new PaperMarioItemFood(0, 20, PM).setUnlocalizedName("papermario.bigCookie").setTextureName("papermario:big_cookie");
    public static final Item cake = new PaperMarioItemFood(0, 15, PM).setUnlocalizedName("papermario.cake").setTextureName("papermario:cake");
    public static final Item egg_missile = new ItemDamageThrown(6, PM).setUnlocalizedName("papermario.eggMissile").setTextureName("papermario:egg_missile");
    public static final Item lime_candy = new PaperMarioItemFood(0, 20, PM).setUnlocalizedName("papermario.limeCandy").setTextureName("papermario:lime_candy");
    public static final Item coco_pop = new PaperMarioItemFood(3, 15, PM).setUnlocalizedName("papermario.cocoPop").setTextureName("papermario:coco_pop");
    public static final Item lemon_candy = new PaperMarioItemFood(5, 15, PM).setUnlocalizedName("papermario.lemonCandy").setTextureName("papermario:lemon_candy");
    public static final Item jelly_pop = new PaperMarioItemFood(0, 64, PM).setUnlocalizedName("papermario.jellyPop").setTextureName("papermario:jelly_pop");
    public static final Item strange_cake = new ItemStrangeCake();
    public static final Item kooky_cookie = new PaperMarioItemFood(0, 15, PM).setUnlocalizedName("papermario.kookyCookie").setTextureName("papermario:kooky_cookie");
    public static final Item frozen_fries = new PaperMarioItemFood(15, 0, PM).setUnlocalizedName("papermario.frozenFries").setTextureName("papermario:frozen_fries");
    public static final Item potato_salad = new PaperMarioItemFood(10, 0, PM).setUnlocalizedName("papermario.potatoSalad").setTextureName("papermario:potato_salad");
    public static final Item nutty_cake = new PaperMarioItemFood(0, 10, PM).setUnlocalizedName("papermario.nuttyCake").setTextureName("papermario:nutty_cake");
    public static final Item boiled_egg = new PaperMarioItemFood(8, 8, PM).setUnlocalizedName("papermario.boiledEgg").setTextureName("papermario:boiled_egg");
    public static final Item yoshi_cookie = new PaperMarioItemFood(15, 15, PM).setUnlocalizedName("papermario.yoshiCookie").setTextureName("papermario:yoshi_cookie");
    public static final Item evil_yoshi_cookie = new PaperMarioItemFood(-15, -15, PM).setAlwaysEdible().setUnlocalizedName("papermario.yoshiCookieEvil").setTextureName("papermario:evil_yoshi_cookie");

    /// PAPER MARIO: THE THOUSAND YEAR DOOR ///

    public static final Item fright_mask = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.frightMask").setTextureName("papermario:fright_mask");
    public static final Item repel_cape = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.repelCape").setTextureName("papermario:repel_cape");
    public static final Item tasty_tonic = new ItemTastyTonic();
    public static final Item jammin_jelly = new PaperMarioItemFood(0, 50, PM, PMTTYD).setUnlocalizedName("papermario.jamminJelly").setTextureName("papermario:jammin_jelly");
    public static final Item ruin_powder = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.ruinPowder").setTextureName("papermario:ruin_powder");
    public static final Item boos_sheet = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.boosSheet").setTextureName("papermario:boos_sheet");
    public static final Item mr_softener = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.mrSoftener").setTextureName("papermario:mr_softener");
    public static final Item pow_block = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.powBlock").setTextureName("papermario:pow_block");
    public static final Item earth_quake = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.earthQuake").setTextureName("papermario:earth_quake");
    public static final Item hp_drain = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.hpDrain").setTextureName("papermario:hp_drain");
    public static final Item stop_watch = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.stopWatch").setTextureName("papermario:stop_watch");
    public static final Item sleepy_sheep = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.sleepySheep").setTextureName("papermario:sleepy_sheep");
    public static final Item mystery = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.mystery").setTextureName("papermario:mystery");
    public static final Item mini_mr_mini = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.miniMrMini").setTextureName("papermario:mini_mr_mini");
    public static final Item maple_syrup = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.mapleSyrup").setTextureName("papermario:maple_syrup");
    public static final Item ice_storm = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.iceStorm").setTextureName("papermario:ice_storm");
    public static final Item shooting_star = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.shootingStar").setTextureName("papermario:shooting_star");
    public static final Item gradual_syrup = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.gradualSyrup").setTextureName("papermario:gradual_syrup");
    public static final Item volt_shroom = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.voltShroom").setTextureName("papermario:volt_shroom");
    public static final Item dried_shroom = new PaperMarioItemFood(1, 0, PM, PMTTYD, SPM).setUnlocalizedName("papermario.driedShroom").setTextureName("papermario:dried_shroom");
    public static final Item slow_shroom = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.slowShroom").setTextureName("papermario:slow_shroom");
    public static final Item life_shroom = new PaperMarioItem(PM, PMTTYD, SPM).setMaxStackSize(1).setUnlocalizedName("papermario.lifeShroom").setTextureName("papermario:life_shroom");
    public static final Item ultra_shroom = new PaperMarioItemFood(50, 0, PM, PMTTYD, SPM).setUnlocalizedName("papermario.ultraShroom").setTextureName("papermario:ultra_shroom");
    public static final Item super_shroom = new PaperMarioItemFood(10, 0, PM, PMTTYD, SPM).setUnlocalizedName("papermario.superShroom").setTextureName("papermario:super_shroom");
    public static final Item mushroom = new PaperMarioItemFood(5, 0, PM, PMTTYD, SPM).setUnlocalizedName("papermario.mushroom").setTextureName("papermario:mushroom");
    public static final Item point_swap = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.pointSwap").setTextureName("papermario:point_swap");
    public static final Item honey_syrup = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.honeySyrup").setTextureName("papermario:honey_syrup");
    public static final Item dizzy_dial = new ItemDizzyDial();
    public static final Item thunder_bolt = new PaperMarioItem(PM, PMTTYD).setUnlocalizedName("papermario.thunderBolt").setTextureName("papermario:thunder_bolt");
    public static final Item fire_flower = new PaperMarioItem(PM, PMTTYD).setUnlocalizedName("papermario.fireFlower").setTextureName("papermario:fire_flower");
    public static final Item thunder_rage = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.thunderRage").setTextureName("papermario:thunder_rage");
    public static final Item power_punch = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.powerPunch").setTextureName("papermario:power_punch");
    public static final Item courage_shell = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.courageShell").setTextureName("papermario:courage_shell");
    public static final Item whacka_bump = new PaperMarioItemFood(25, 25, PM, PMTTYD, SPM).setUnlocalizedName("papermario.whackaBump").setTextureName("papermario:whacka_bump");
    public static final Item gold_bar_x3 = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.goldBarx3").setTextureName("papermario:gold_bar_x3");
    public static final Item gold_bar = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.goldBar").setTextureName("papermario:gold_bar");
    public static final Item coconut = new ItemDamageThrown(3, PM, PMTTYD).setUnlocalizedName("papermario.coconut").setTextureName("papermario:coconut");
    public static final Item hot_dog = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.hotDog").setTextureName("papermario:hot_dog");
    public static final Item couples_cake = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.couplesCake").setTextureName("papermario:couples_cake");
    public static final Item love_pudding = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.lovePudding").setTextureName("papermario:love_pudding");
    public static final Item spicy_pasta = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.spicyPasta").setTextureName("papermario:spicy_pasta");
    public static final Item fire_pop = new PaperMarioItemFood(-1, 20, PM, PMTTYD).setUnlocalizedName("papermario.firePop").setTextureName("papermario:fire_pop");
    public static final Item electro_pop = new PaperMarioItem(PM, PMTTYD, SPM).setUnlocalizedName("papermario.electroPop").setTextureName("papermario:electro_pop");
    public static final Item zess_cookie = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessCookie").setTextureName("papermario:zess_cookie");
    public static final Item koopa_bun = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.koopaBun").setTextureName("papermario:koopa_bun");
    public static final Item horsetail = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.horsetail").setTextureName("papermario:horsetail");
    public static final Item egg_bomb = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.eggBomb").setTextureName("papermario:egg_bomb");
    public static final Item choco_cake = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.chocoCake").setTextureName("papermario:choco_cake");
    public static final Item spaghetti = new PaperMarioItemFood(6, 4, PM, PMTTYD).setUnlocalizedName("papermario.spaghetti").setTextureName("papermario:spaghetti");
    public static final Item fruit_parfait = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.fruitParfait").setTextureName("papermario:fruit_parfait");
    public static final Item peachy_peach = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.peachyPeach").setTextureName("papermario:peachy_peach");
    public static final Item mousse_cake = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.mousseCake").setTextureName("papermario:mousse_cake");
    public static final Item cake_mix = new PaperMarioItemFood(0, 1, PM, PMTTYD, SPM).setUnlocalizedName("papermario.cakeMix").setTextureName("papermario:cake_mix");
    public static final Item fried_egg = new PaperMarioItemFood(10, 0, PM, PMTTYD, SPM).setUnlocalizedName("papermario.friedEgg").setTextureName("papermario:fried_egg");
    public static final Item mango_delight = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.mangoDelight").setTextureName("papermario:mango_delight");
    public static final Item shroom_cake = new PaperMarioItemFood(10, 10, PM, PMTTYD, SPM).setUnlocalizedName("papermario.shroomCake").setTextureName("papermario:shroom_cake");
    public static final Item hot_sauce = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.hotSauce").setTextureName("papermario:hot_sauce");
    public static final Item koopa_tea = new ItemKoopaTea();
    public static final Item fresh_juice = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.freshJuice").setTextureName("papermario:fresh_juice");
    public static final Item poison_mushroom = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.poisonMushroom").setTextureName("papermario:poison_mushroom");
    public static final Item mushroom_crepe = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.mushroomCrepe").setTextureName("papermario:mushroom_crepe");
    public static final Item inky_sauce = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.inkySauce").setTextureName("papermario:inky_sauce");
    // trial stew: set saturation to 0 and reduce enough hunger to prevent regen
    public static final Item trial_stew = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.trialStew").setTextureName("papermario:trial_stew");
    public static final Item peach_tart = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.peachTart").setTextureName("papermario:peach_tart");
    public static final Item omelette_meal = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.omeletteMeal").setTextureName("papermario:omelette_meal");
    public static final Item heartful_cake = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.heartfulCake").setTextureName("papermario:heartful_cake");
    public static final Item shroom_broth = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.shroomBroth").setTextureName("papermario:shroom_broth");
    public static final Item koopasta = new PaperMarioItemFood(7, 7, PM, PMTTYD, SPM).setUnlocalizedName("papermario.koopasta").setTextureName("papermario:koopasta");
    public static final Item ink_pasta = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.inkPasta").setTextureName("papermario:ink_pasta");
    public static final Item meteor_meal = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.meteorMeal").setTextureName("papermario:meteor_meal");
    public static final Item healthy_salad = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.healthySalad").setTextureName("papermario:healthy_salad");
    public static final Item jelly_candy = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.jellyCandy").setTextureName("papermario:jelly_candy");
    public static final Item honey_candy = new PaperMarioItemFood(0, 20, PM, PMTTYD, SPM).setUnlocalizedName("papermario.honeyCandy").setTextureName("papermario:honey_candy");
    public static final Item coco_candy = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.cocoCandy").setTextureName("papermario:coco_candy");
    public static final Item golden_leaf = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.goldenLeaf").setTextureName("papermario:golden_leaf");
    public static final Item fresh_pasta = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.freshPasta").setTextureName("papermario:fresh_pasta");
    public static final Item keel_mango = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.keelMango").setTextureName("papermario:keel_mango");
    public static final Item mystic_egg = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.mysticEgg").setTextureName("papermario:mystic_egg");
    public static final Item spite_pouch = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.spitePouch").setTextureName("papermario:spite_pouch");
    public static final Item courage_meal = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.courageMeal").setTextureName("papermario:courage_meal");
    public static final Item zess_dynamite = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessDynamite").setTextureName("papermario:zess_dynamite");
    public static final Item zess_special = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessSpecial").setTextureName("papermario:zess_special");
    public static final Item zess_dinner = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessDinner").setTextureName("papermario:zess_dinner");
    public static final Item zess_tea = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessTea").setTextureName("papermario:zess_tea");
    public static final Item jelly_ultra = new PaperMarioItemFood(50, 50, PM, PMTTYD).setUnlocalizedName("papermario.jellyUltra").setTextureName("papermario:jelly_ultra");
    public static final Item maple_ultra = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.mapleUltra").setTextureName("papermario:maple_ultra");
    public static final Item honey_ultra = new PaperMarioItemFood(50, 5, PM, PMTTYD).setUnlocalizedName("papermario.honeyUltra").setTextureName("papermario:honey_ultra");
    public static final Item jelly_super = new PaperMarioItemFood(10, 50, PM, PMTTYD).setUnlocalizedName("papermario.jellySuper").setTextureName("papermario:jelly_super");
    public static final Item maple_super = new PaperMarioItemFood(10, 10, PM, PMTTYD).setUnlocalizedName("papermario.mapleSuper").setTextureName("papermario:maple_super");
    public static final Item honey_super = new PaperMarioItemFood(10, 5, PM, PMTTYD, SPM).setUnlocalizedName("papermario.honeySuper").setTextureName("papermario:honey_super");
    public static final Item jelly_shroom = new PaperMarioItemFood(5, 50, PM, PMTTYD).setUnlocalizedName("papermario.jellyShroom").setTextureName("papermario:jelly_shroom");
    public static final Item maple_shroom = new PaperMarioItemFood(5, 10, PM, PMTTYD).setUnlocalizedName("papermario.mapleShroom").setTextureName("papermario:maple_shroom");
    public static final Item honey_shroom = new PaperMarioItemFood(5, 5, PM, PMTTYD, SPM).setUnlocalizedName("papermario.honeyShroom").setTextureName("papermario:honey_shroom");
    public static final Item snow_bunny = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.snowBunny").setTextureName("papermario:snow_bunny");
    public static final Item space_food = new PaperMarioItem(PMTTYD, SPM).setUnlocalizedName("papermario.spaceFood").setTextureName("papermario:space_food");
    public static final Item spicy_soup = new PaperMarioItemFood(4, 4, PM, PMTTYD, SPM).setUnlocalizedName("papermario.spicySoup").setTextureName("papermario:spicy_soup");
    public static final Item mistake = new PaperMarioItemFood(1, 1, PM, PMTTYD, SPM).setUnlocalizedName("papermario.mistake").setTextureName("papermario:mistake");
    public static final Item zess_deluxe = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessDeluxe").setTextureName("papermario:zess_deluxe");
    public static final Item shroom_steak = new PaperMarioItemFood(30, 10, PM, PMTTYD, SPM).setUnlocalizedName("papermario.shroomSteak").setTextureName("papermario:shroom_steak");
    public static final Item shroom_roast = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.shroomRoast").setTextureName("papermario:shroom_roast");
    public static final Item icicle_pop = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.iciclePop").setTextureName("papermario:icicle_pop");
    public static final Item zess_frappe = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.zessFrappe").setTextureName("papermario:zess_frappe");
    public static final Item dried_bouquet = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.driedBouquet").setTextureName("papermario:dried_bouquet");
    public static final Item coconut_bomb = new PaperMarioItem(PMTTYD).setUnlocalizedName("papermario.coconutBomb").setTextureName("papermario:coconut_bomb");

    /// SUPER PAPER MARIO ///

    public static final Item bonein_cut = new PaperMarioItem(SPM).setUnlocalizedName("papermario.boneinCut").setTextureName("papermario:bonein_cut");
    public static final Item fire_burst = new PaperMarioItem(SPM).setUnlocalizedName("papermario.fireBurst").setTextureName("papermario:fire_burst");
    public static final Item ghost_shroom = new PaperMarioItem(SPM).setUnlocalizedName("papermario.ghostShroom").setTextureName("papermario:ghost_shroom");
    public static final Item mighty_tonic = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mightyTonic").setTextureName("papermario:mighty_tonic");
    public static final Item shell_shock = new PaperMarioItem(SPM).setUnlocalizedName("papermario.shellShock").setTextureName("papermario:shell_shock");
    public static final Item block_block = new PaperMarioItem(SPM).setUnlocalizedName("papermario.blockBlock").setTextureName("papermario:block_block");
    public static final Item big_egg = new PaperMarioItem(SPM).setUnlocalizedName("papermario.bigEgg").setTextureName("papermario:big_egg");
    public static final Item black_apple = new PaperMarioItem(SPM).setUnlocalizedName("papermario.blackApple").setTextureName("papermario:black_apple");
    public static final Item blue_apple = new PaperMarioItem(SPM).setUnlocalizedName("papermario.blueApple").setTextureName("papermario:blue_apple");
    public static final Item dayzee_tear = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dayzeeTear").setTextureName("papermario:dayzee_tear");
    public static final Item fresh_pasta_bunch = new PaperMarioItem(SPM).setUnlocalizedName("papermario.freshPastaBunch").setTextureName("papermario:fresh_pasta_bunch");
    public static final Item fresh_veggie = new PaperMarioItem(SPM).setUnlocalizedName("papermario.freshVeggie").setTextureName("papermario:fresh_veggie");
    public static final Item honey_jar = new PaperMarioItem(SPM).setUnlocalizedName("papermario.honeyJar").setTextureName("papermario:honey_jar");
    public static final Item longlast_shake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.longlastShake").setTextureName("papermario:longlast_shake");
    public static final Item mild_cocoa_bean = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mildCocoaBean").setTextureName("papermario:mild_cocoa_bean");
    public static final Item pink_apple = new PaperMarioItem(SPM).setUnlocalizedName("papermario.pinkApple").setTextureName("papermario:pink_apple");
    public static final Item power_steak = new PaperMarioItem(SPM).setUnlocalizedName("papermario.powerSteak").setTextureName("papermario:power_steak");
    public static final Item primordial_fruit = new PaperMarioItem(SPM).setUnlocalizedName("papermario.primordialFruit").setTextureName("papermario:primordial_fruit");
    public static final Item red_apple = new PaperMarioItem(SPM).setUnlocalizedName("papermario.redApple").setTextureName("papermario:red_apple");
    public static final Item sap_soup = new PaperMarioItem(SPM).setUnlocalizedName("papermario.sapSoup").setTextureName("papermario:sap_soup");
    public static final Item shroom_shake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.shroomShake").setTextureName("papermario:shroom_shake");
    public static final Item slimy_shroom = new PaperMarioItem(SPM).setUnlocalizedName("papermario.slimyShroom").setTextureName("papermario:slimy_shroom");
    public static final Item smelly_herb = new PaperMarioItem(SPM).setUnlocalizedName("papermario.smellyHerb").setTextureName("papermario:smelly_herb");
    public static final Item super_shroom_shake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.superShroomShake").setTextureName("papermario:super_shroom_shake");
    public static final Item ultra_shroom_shake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.ultraShroomShake").setTextureName("papermario:ultra_shroom_shake");
    public static final Item yellow_apple = new PaperMarioItem(SPM).setUnlocalizedName("papermario.yellowApple").setTextureName("papermario:yellow_apple");
    public static final Item catch_card = new PaperMarioItem(SPM).setUnlocalizedName("papermario.catchCard").setTextureName("papermario:catch_card");
    public static final Item catch_card_sp = new PaperMarioItem(SPM).setUnlocalizedName("papermario.catchCardSP").setTextureName("papermario:catch_card_sp");
    public static final Item gold_medal = new PaperMarioItem(SPM).setUnlocalizedName("papermario.goldMedal").setTextureName("papermario:gold_medal");
    public static final Item hp_plus = new PaperMarioItem(SPM).setUnlocalizedName("papermario.hpPlus").setTextureName("papermario:hp_plus");
    public static final Item mega_star = new PaperMarioItem(SPM).setUnlocalizedName("papermario.megaStar").setTextureName("papermario:mega_star");
    public static final Item mystery_box = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mysteryBox").setTextureName("papermario:mystery_box");
    public static final Item pal_pill = new PaperMarioItem(SPM).setUnlocalizedName("papermario.palPill").setTextureName("papermario:pal_pill");
    public static final Item poison_shroom = new PaperMarioItem(SPM).setUnlocalizedName("papermario.poisonShroom").setTextureName("papermario:poison_shroom");
    public static final Item power_plus = new PaperMarioItem(SPM).setUnlocalizedName("papermario.powerPlus").setTextureName("papermario:power_plus");
    public static final Item slow_flower = new PaperMarioItem(SPM).setUnlocalizedName("papermario.slowFlower").setTextureName("papermario:slow_flower");
    public static final Item speed_flower = new PaperMarioItem(SPM).setUnlocalizedName("papermario.speedFlower").setTextureName("papermario:speed_flower");
    public static final Item star_medal = new PaperMarioItem(SPM).setUnlocalizedName("papermario.starMedal").setTextureName("papermario:star_medal");

    public static final Item block_meal = new PaperMarioItem(SPM).setUnlocalizedName("papermario.blockMeal").setTextureName("papermario:block_meal");
    public static final Item dangerous_delight = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dangerousDelight").setTextureName("papermario:dangerous_delight");
    public static final Item dayzee_syrup = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dayzeeSyrup").setTextureName("papermario:dayzee_syrup");
    public static final Item golden_meal = new PaperMarioItem(SPM).setUnlocalizedName("papermario.goldenMeal").setTextureName("papermario:golden_meal");
    public static final Item hamburger = new PaperMarioItem(SPM).setUnlocalizedName("papermario.hamburger").setTextureName("papermario:hamburger");
    public static final Item herb_tea = new PaperMarioItem(SPM).setUnlocalizedName("papermario.herbTea").setTextureName("papermario:herb_tea");
    public static final Item inky_soup = new PaperMarioItem(SPM).setUnlocalizedName("papermario.inkySoup").setTextureName("papermario:inky_soup");
    public static final Item mango_juice = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mangoJuice").setTextureName("papermario:mango_juice");
    public static final Item megaton_dinner = new PaperMarioItem(SPM).setUnlocalizedName("papermario.megatonDinner").setTextureName("papermario:megaton_dinner");
    public static final Item miracle_dinner = new PaperMarioItem(SPM).setUnlocalizedName("papermario.miracleDinner").setTextureName("papermario:miracle_dinner");
    public static final Item peach_juice = new PaperMarioItem(SPM).setUnlocalizedName("papermario.peachJuice").setTextureName("papermario:peach_juice");
    public static final Item roast_horsetail = new PaperMarioItem(SPM).setUnlocalizedName("papermario.roastHorsetail").setTextureName("papermario:roast_horsetail");
    public static final Item roast_shroom_dish = new PaperMarioItem(SPM).setUnlocalizedName("papermario.roastShroomDish").setTextureName("papermario:roast_shroom_dish");
    public static final Item roast_whacka_bump = new PaperMarioItem(SPM).setUnlocalizedName("papermario.roastWhackaBump").setTextureName("papermario:roast_whacka_bump");
    public static final Item sap_syrup = new PaperMarioItem(SPM).setUnlocalizedName("papermario.sapSyrup").setTextureName("papermario:sap_syrup");
    public static final Item sky_juice = new PaperMarioItem(SPM).setUnlocalizedName("papermario.skyJuice").setTextureName("papermario:sky_juice");
    public static final Item slimy_extract = new PaperMarioItem(SPM).setUnlocalizedName("papermario.slimyExtract").setTextureName("papermario:slimy_extract");
    public static final Item snow_cone = new PaperMarioItem(SPM).setUnlocalizedName("papermario.snowCone").setTextureName("papermario:snow_cone");
    public static final Item spaghetti_plate = new PaperMarioItem(SPM).setUnlocalizedName("papermario.spaghettiPlate").setTextureName("papermario:spaghetti_plate");
    public static final Item spit_roast = new PaperMarioItem(SPM).setUnlocalizedName("papermario.spitRoast").setTextureName("papermario:spit_roast");
    public static final Item sweet_cookie_snack = new PaperMarioItem(SPM).setUnlocalizedName("papermario.sweetCookieSnack").setTextureName("papermario:sweet_cookie_snack");
    public static final Item town_special = new PaperMarioItem(SPM).setUnlocalizedName("papermario.townSpecial").setTextureName("papermario:town_special");
    public static final Item warm_cocoa = new PaperMarioItem(SPM).setUnlocalizedName("papermario.warmCocoa").setTextureName("papermario:warm_cocoa");

    public static final Item awesome_snack = new PaperMarioItem(SPM).setUnlocalizedName("papermario.awesomeSnack").setTextureName("papermario:awesome_snack");
    public static final Item berry_snow_bunny = new PaperMarioItem(SPM).setUnlocalizedName("papermario.berrySnowBunny").setTextureName("papermario:berry_snow_bunny");
    public static final Item chocolate_cake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.chocolateCake").setTextureName("papermario:chocolate_cake");
    public static final Item choco_pasta_dish = new PaperMarioItem(SPM).setUnlocalizedName("papermario.chocoPastaDish").setTextureName("papermario:choco_pasta_dish");
    public static final Item dyllis_breakfast = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dyllisBreakfast").setTextureName("papermario:dyllis_breakfast");
    public static final Item dyllis_deluxe = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dyllisDeluxe").setTextureName("papermario:dyllis_deluxe");
    public static final Item dyllis_dinner = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dyllisDinner").setTextureName("papermario:dyllis_dinner");
    public static final Item dyllis_dynamite = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dyllisDynamite").setTextureName("papermario:dyllis_dynamite");
    public static final Item dyllis_lunch = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dyllisLunch").setTextureName("papermario:dyllis_lunch");
    public static final Item dyllis_special = new PaperMarioItem(SPM).setUnlocalizedName("papermario.dyllisSpecial").setTextureName("papermario:dyllis_special");
    public static final Item emergency_ration = new PaperMarioItem(SPM).setUnlocalizedName("papermario.emergencyRation").setTextureName("papermario:emergency_ration");
    public static final Item fruity_cake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.fruityCake").setTextureName("papermario:fruity_cake");
    public static final Item fruity_hamburger = new PaperMarioItem(SPM).setUnlocalizedName("papermario.fruityHamburger").setTextureName("papermario:fruity_hamburger");
    public static final Item fruity_punch = new PaperMarioItem(SPM).setUnlocalizedName("papermario.fruityPunch").setTextureName("papermario:fruity_punch");
    public static final Item fruity_shroom = new PaperMarioItem(SPM).setUnlocalizedName("papermario.fruityShroom").setTextureName("papermario:fruity_shroom");
    public static final Item gingerbread_house = new PaperMarioItem(SPM).setUnlocalizedName("papermario.gingerbreadHouse").setTextureName("papermario:gingerbread_house");
    public static final Item golden_chocobar = new PaperMarioItem(SPM).setUnlocalizedName("papermario.goldenChocobar").setTextureName("papermario:golden_chocobar");
    public static final Item gorgeous_steak = new PaperMarioItem(SPM).setUnlocalizedName("papermario.gorgeousSteak").setTextureName("papermario:gorgeous_steak");
    public static final Item heavy_meal = new PaperMarioItem(SPM).setUnlocalizedName("papermario.heavyMeal").setTextureName("papermario:heavy_meal");
    public static final Item horsetail_tart = new PaperMarioItem(SPM).setUnlocalizedName("papermario.horsetailTart").setTextureName("papermario:horsetail_tart");
    public static final Item ink_pasta_dish = new PaperMarioItem(SPM).setUnlocalizedName("papermario.inkPastaDish").setTextureName("papermario:ink_pasta_dish");
    public static final Item koopa_dumpling = new PaperMarioItem(SPM).setUnlocalizedName("papermario.koopaDumpling").setTextureName("papermario:koopa_dumpling");
    public static final Item koopa_pilaf = new PaperMarioItem(SPM).setUnlocalizedName("papermario.koopaPilaf").setTextureName("papermario:koopa_pilaf");
    public static final Item love_noodle_dish = new PaperMarioItem(SPM).setUnlocalizedName("papermario.loveNoodleDish").setTextureName("papermario:love_noodle_dish");
    public static final Item lovely_chocolate = new PaperMarioItem(SPM).setUnlocalizedName("papermario.lovelyChocolate").setTextureName("papermario:lovely_chocolate");
    public static final Item luxurious_set = new PaperMarioItem(SPM).setUnlocalizedName("papermario.luxuriousSet").setTextureName("papermario:luxurious_set");
    public static final Item mango_pudding = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mangoPudding").setTextureName("papermario:mango_pudding");
    public static final Item meat_pasta_dish = new PaperMarioItem(SPM).setUnlocalizedName("papermario.meatPastaDish").setTextureName("papermario:meat_pasta_dish");
    public static final Item mixed_shake = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mixedShake").setTextureName("papermario:mixed_shake");
    public static final Item mousse = new PaperMarioItem(SPM).setUnlocalizedName("papermario.mousse").setTextureName("papermario:mousse");
    public static final Item odd_dinner = new PaperMarioItem(SPM).setUnlocalizedName("papermario.oddDinner").setTextureName("papermario:odd_dinner");
    public static final Item omelette_plate = new PaperMarioItem(SPM).setUnlocalizedName("papermario.omelettePlate").setTextureName("papermario:omelette_plate");
    public static final Item primordial_dinner = new PaperMarioItem(SPM).setUnlocalizedName("papermario.primordialDinner").setTextureName("papermario:primordial_dinner");
    public static final Item sap_muffin = new PaperMarioItem(SPM).setUnlocalizedName("papermario.sapMuffin").setTextureName("papermario:sap_muffin");
    public static final Item shroom_chocobar = new PaperMarioItem(SPM).setUnlocalizedName("papermario.shroomChocoBar").setTextureName("papermario:shroom_chocobar");
    public static final Item shroom_delicacy = new PaperMarioItem(SPM).setUnlocalizedName("papermario.shroomDelicacy").setTextureName("papermario:shroom_delicacy");
    public static final Item shroom_pudding = new PaperMarioItem(SPM).setUnlocalizedName("papermario.shroomPudding").setTextureName("papermario:shroom_pudding");
    public static final Item spicy_dinner = new PaperMarioItem(SPM).setUnlocalizedName("papermario.spicyDinner").setTextureName("papermario:spicy_dinner");
    public static final Item spicy_pasta_dish = new PaperMarioItem(SPM).setUnlocalizedName("papermario.spicyPastaDish").setTextureName("papermario:spicy_pasta_dish");
    public static final Item stamina_juice = new PaperMarioItem(SPM).setUnlocalizedName("papermario.staminaJuice").setTextureName("papermario:stamina_juice");
    public static final Item standard_chocolate = new PaperMarioItem(SPM).setUnlocalizedName("papermario.standardChocolate").setTextureName("papermario:standard_chocolate");
    public static final Item sweet_chocobar = new PaperMarioItem(SPM).setUnlocalizedName("papermario.sweetChocobar").setTextureName("papermario:sweet_chocobar");
    public static final Item veggie_set = new PaperMarioItem(SPM).setUnlocalizedName("papermario.veggieSet").setTextureName("papermario:veggie_set");
    public static final Item volcano_shroom = new PaperMarioItem(SPM).setUnlocalizedName("papermario.volcanoShroom").setTextureName("papermario:volcano_shroom");
    public static final Item weird_extract = new PaperMarioItem(SPM).setUnlocalizedName("papermario.weirdExtract").setTextureName("papermario:weird_extract");

    public static void registerItems() {
        /// PAPER MARIO ///
        registerItem(snowman_doll, "snowman_doll");
        registerItem(pebble, "pebble");
        registerItem(dusty_hammer, "dusty_hammer");
        registerItem(stone_cap, "stone_cap");
        registerItem(apple, "apple");
        registerItem(repel_gel, "repel_gel");
        registerItem(fright_jar, "fright_jar");
        registerItem(super_soda, "super_soda");
        registerItem(lemon, "lemon");
        registerItem(lime, "lime");
        registerItem(blue_berry, "blue_berry");
        registerItem(red_berry, "red_berry");
        registerItem(yellow_berry, "yellow_berry");
        registerItem(bubble_berry, "bubble_berry");
        registerItem(goomnut, "goomnut");
        registerItem(koopa_leaf, "koopa_leaf");
        registerItem(dried_pasta, "dried_pasta");
        registerItem(dried_fruit, "dried_fruit");
        registerItem(strange_leaf, "strange_leaf");
        registerItem(egg, "egg");
        registerItem(melon, "melon");
        registerItem(stinky_herb, "stinky_herb");
        registerItem(iced_potato, "iced_potato");
        registerItem(apple_pie, "apple_pie");
        registerItem(fried_shroom, "fried_shroom");
        registerItem(hot_shroom, "hot_shroom");
        registerItem(sweet_shroom, "sweet_shroom");
        registerItem(yummy_meal, "yummy_meal");
        registerItem(healthy_juice, "healthy_juice");
        registerItem(bland_meal, "bland_meal");
        registerItem(deluxe_feast, "deluxe_feast");
        registerItem(special_shake, "special_shake");
        registerItem(big_cookie, "big_cookie");
        registerItem(cake, "cake");
        registerItem(egg_missile, "egg_missile");
        registerItem(lime_candy, "lime_candy");
        registerItem(coco_pop, "coco_pop");
        registerItem(lemon_candy, "lemon_candy");
        registerItem(jelly_pop, "jelly_pop");
        registerItem(strange_cake, "strange_cake");
        registerItem(kooky_cookie, "kooky_cookie");
        registerItem(frozen_fries, "frozen_fries");
        registerItem(potato_salad, "potato_salad");
        registerItem(nutty_cake, "nutty_cake");
        registerItem(boiled_egg, "boiled_egg");
        registerItem(yoshi_cookie, "yoshi_cookie");
        registerItem(evil_yoshi_cookie, "evil_yoshi_cookie");
        /// PAPER MARIO: THE THOUSAND YEAR DOOR ///
        registerItem(fright_mask, "fright_mask");
        registerItem(repel_cape, "repel_cape");
        registerItem(tasty_tonic, "tasty_tonic");
        registerItem(jammin_jelly, "jammin_jelly");
        registerItem(ruin_powder, "ruin_powder");
        registerItem(boos_sheet, "boos_sheet");
        registerItem(mr_softener, "mr_softener");
        registerItem(pow_block, "pow_block");
        registerItem(earth_quake, "earth_quake");
        registerItem(hp_drain, "hp_drain");
        registerItem(stop_watch, "stop_watch");
        registerItem(sleepy_sheep, "sleepy_sheep");
        registerItem(mystery, "mystery");
        registerItem(mini_mr_mini, "mini_mr_mini");
        registerItem(maple_syrup, "maple_syrup");
        registerItem(ice_storm, "ice_storm");
        registerItem(shooting_star, "shooting_star");
        registerItem(gradual_syrup, "gradual_syrup");
        registerItem(volt_shroom, "volt_shroom");
        registerItem(dried_shroom, "dried_shroom");
        registerItem(slow_shroom, "slow_shroom");
        registerItem(life_shroom, "life_shroom");
        registerItem(ultra_shroom, "ultra_shroom");
        registerItem(super_shroom, "super_shroom");
        registerItem(mushroom, "mushroom");
        registerItem(point_swap, "point_swap");
        registerItem(honey_syrup, "honey_syrup");
        registerItem(dizzy_dial, "dizzy_dial");
        registerItem(thunder_bolt, "thunder_bolt");
        registerItem(fire_flower, "fire_flower");
        registerItem(thunder_rage, "thunder_rage");
        registerItem(power_punch, "power_punch");
        registerItem(courage_shell, "courage_shell");
        registerItem(whacka_bump, "whacka_bump");
        registerItem(gold_bar_x3, "gold_bar_x3");
        registerItem(gold_bar, "gold_bar");
        registerItem(coconut, "coconut");
        registerItem(hot_dog, "hot_dog");
        registerItem(couples_cake, "couples_cake");
        registerItem(love_pudding, "love_pudding");
        registerItem(spicy_pasta, "spicy_pasta");
        registerItem(fire_pop, "fire_pop");
        registerItem(electro_pop, "electro_pop");
        registerItem(zess_cookie, "zess_cookie");
        registerItem(koopa_bun, "koopa_bun");
        registerItem(horsetail, "horsetail");
        registerItem(egg_bomb, "egg_bomb");
        registerItem(choco_cake, "choco_cake");
        registerItem(spaghetti, "spaghetti");
        registerItem(fruit_parfait, "fruit_parfait");
        registerItem(peachy_peach, "peachy_peach");
        registerItem(mousse_cake, "mousse_cake");
        registerItem(cake_mix, "cake_mix");
        registerItem(fried_egg, "fried_egg");
        registerItem(mango_delight, "mango_delight");
        registerItem(shroom_cake, "shroom_cake");
        registerItem(hot_sauce, "hot_sauce");
        registerItem(koopa_tea, "koopa_tea");
        registerItem(fresh_juice, "fresh_juice");
        registerItem(poison_mushroom, "poison_mushroom");
        registerItem(mushroom_crepe, "mushroom_crepe");
        registerItem(inky_sauce, "inky_sauce");
        registerItem(trial_stew, "trial_stew");
        registerItem(peach_tart, "peach_tart");
        registerItem(omelette_meal, "omelette_meal");
        registerItem(heartful_cake, "heartful_cake");
        registerItem(shroom_broth, "shroom_broth");
        registerItem(koopasta, "koopasta");
        registerItem(ink_pasta, "ink_pasta");
        registerItem(meteor_meal, "meteor_meal");
        registerItem(healthy_salad, "healthy_salad");
        registerItem(jelly_candy, "jelly_candy");
        registerItem(honey_candy, "honey_candy");
        registerItem(coco_candy, "coco_candy");
        registerItem(golden_leaf, "golden_leaf");
        registerItem(fresh_pasta, "fresh_pasta");
        registerItem(keel_mango, "keel_mango");
        registerItem(mystic_egg, "mystic_egg");
        registerItem(spite_pouch, "spite_pouch");
        registerItem(courage_meal, "courage_meal");
        registerItem(zess_dynamite, "zess_dynamite");
        registerItem(zess_special, "zess_special");
        registerItem(zess_dinner, "zess_dinner");
        registerItem(zess_tea, "zess_tea");
        registerItem(jelly_ultra, "jelly_ultra");
        registerItem(maple_ultra, "maple_ultra");
        registerItem(honey_ultra, "honey_ultra");
        registerItem(jelly_super, "jelly_super");
        registerItem(maple_super, "maple_super");
        registerItem(honey_super, "honey_super");
        registerItem(jelly_shroom, "jelly_shroom");
        registerItem(maple_shroom, "maple_shroom");
        registerItem(honey_shroom, "honey_shroom");
        registerItem(snow_bunny, "snow_bunny");
        registerItem(space_food, "space_food");
        registerItem(spicy_soup, "spicy_soup");
        registerItem(mistake, "mistake");
        registerItem(zess_deluxe, "zess_deluxe");
        registerItem(shroom_steak, "shroom_steak");
        registerItem(shroom_roast, "shroom_roast");
        registerItem(icicle_pop, "icicle_pop");
        registerItem(zess_frappe, "zess_frappe");
        registerItem(dried_bouquet, "dried_bouquet");
        registerItem(coconut_bomb, "coconut_bomb");
        /// SUPER PAPER MARIO ///
        registerItem(bonein_cut, "bonein_cut");
        registerItem(fire_burst, "fire_burst");
        registerItem(ghost_shroom, "ghost_shroom");
        registerItem(mighty_tonic, "mighty_tonic");
        registerItem(shell_shock, "shell_shock");
        registerItem(block_block, "block_block");
        registerItem(big_egg, "big_egg");
        registerItem(black_apple, "black_apple");
        registerItem(blue_apple, "blue_apple");
        registerItem(dayzee_tear, "dayzee_tear");
        registerItem(fresh_pasta_bunch, "fresh_pasta_bunch");
        registerItem(fresh_veggie, "fresh_veggie");
        registerItem(honey_jar, "honey_jar");
        registerItem(longlast_shake, "longlast_shake");
        registerItem(mild_cocoa_bean, "mild_cocoa_bean");
        registerItem(pink_apple, "pink_apple");
        registerItem(power_steak, "power_steak");
        registerItem(primordial_fruit, "primordial_fruit");
        registerItem(red_apple, "red_apple");
        registerItem(sap_soup, "sap_soup");
        registerItem(shroom_shake, "shroom_shake");
        registerItem(slimy_shroom, "slimy_shroom");
        registerItem(smelly_herb, "smelly_herb");
        registerItem(super_shroom_shake, "super_shroom_shake");
        registerItem(ultra_shroom_shake, "ultra_shroom_shake");
        registerItem(yellow_apple, "yellow_apple");
        registerItem(catch_card, "catch_card");
        registerItem(catch_card_sp, "catch_card_sp");
        registerItem(gold_medal, "gold_medal");
        registerItem(hp_plus, "hp_plus");
        registerItem(mega_star, "mega_star");
        registerItem(mystery_box, "mystery_box");
        registerItem(pal_pill, "pal_pill");
        registerItem(poison_shroom, "poison_shroom");
        registerItem(power_plus, "power_plus");
        registerItem(slow_flower, "slow_flower");
        registerItem(speed_flower, "speed_flower");
        registerItem(star_medal, "star_medal");

        registerItem(block_meal, "block_meal");
        registerItem(dangerous_delight, "dangerous_delight");
        registerItem(dayzee_syrup, "dayzee_syrup");
        registerItem(golden_meal, "golden_meal");
        registerItem(hamburger, "hamburger");
        registerItem(herb_tea, "herb_tea");
        registerItem(inky_soup, "inky_soup");
        registerItem(mango_juice, "mango_juice");
        registerItem(megaton_dinner, "megaton_dinner");
        registerItem(miracle_dinner, "miracle_dinner");
        registerItem(peach_juice, "peach_juice");
        registerItem(roast_horsetail, "roast_horsetail");
        registerItem(roast_shroom_dish, "roast_shroom_dish");
        registerItem(roast_whacka_bump, "roast_whacka_bump");
        registerItem(sap_syrup, "sap_syrup");
        registerItem(sky_juice, "sky_juice");
        registerItem(slimy_extract, "slimy_extract");
        registerItem(snow_cone, "snow_cone");
        registerItem(spaghetti_plate, "spaghetti_plate");
        registerItem(spit_roast, "spit_roast");
        registerItem(sweet_cookie_snack, "sweet_cookie_snack");
        registerItem(town_special, "town_special");
        registerItem(warm_cocoa, "warm_cocoa");

        registerItem(awesome_snack, "awesome_snack");
        registerItem(berry_snow_bunny, "berry_snow_bunny");
        registerItem(chocolate_cake, "chocolate_cake");
        registerItem(choco_pasta_dish, "choco_pasta_dish");
        registerItem(dyllis_breakfast, "dyllis_breakfast");
        registerItem(dyllis_deluxe, "dyllis_deluxe");
        registerItem(dyllis_dinner, "dyllis_dinner");
        registerItem(dyllis_dynamite, "dyllis_dynamite");
        registerItem(dyllis_lunch, "dyllis_lunch");
        registerItem(dyllis_special, "dyllis_special");
        registerItem(emergency_ration, "emergency_ration");
        registerItem(fruity_cake, "fruity_cake");
        registerItem(fruity_hamburger, "fruity_hamburger");
        registerItem(fruity_punch, "fruity_punch");
        registerItem(fruity_shroom, "fruity_shroom");
        registerItem(gingerbread_house, "gingerbread_house");
        registerItem(golden_chocobar, "golden_chocobar");
        registerItem(gorgeous_steak, "gorgeous_steak");
        registerItem(heavy_meal, "heavy_meal");
        registerItem(horsetail_tart, "horsetail_tart");
        registerItem(ink_pasta_dish, "ink_pasta_dish");
        registerItem(koopa_dumpling, "koopa_dumpling");
        registerItem(koopa_pilaf, "koopa_pilaf");
        registerItem(love_noodle_dish, "love_noodle_dish");
        registerItem(lovely_chocolate, "lovely_chocolate");
        registerItem(luxurious_set, "luxurious_set");
        registerItem(mango_pudding, "mango_pudding");
        registerItem(meat_pasta_dish, "meat_pasta_dish");
        registerItem(mixed_shake, "mixed_shake");
        registerItem(mousse, "mousse");
        registerItem(odd_dinner, "odd_dinner");
        registerItem(omelette_plate, "omelette_plate");
        registerItem(primordial_dinner, "primordial_dinner");
        registerItem(sap_muffin, "sap_muffin");
        registerItem(shroom_chocobar, "shroom_chocobar");
        registerItem(shroom_delicacy, "shroom_delicacy");
        registerItem(shroom_pudding, "shroom_pudding");
        registerItem(spicy_dinner, "spicy_dinner");
        registerItem(spicy_pasta_dish, "spicy_pasta_dish");
        registerItem(stamina_juice, "stamina_juice");
        registerItem(standard_chocolate, "standard_chocolate");
        registerItem(sweet_chocobar, "sweet_chocobar");
        registerItem(veggie_set, "veggie_set");
        registerItem(volcano_shroom, "volcano_shroom");
        registerItem(weird_extract, "weird_extract");
    }

    public static void registerItem(net.minecraft.item.Item item, String name) {
        if (item instanceof PaperMarioItemFood) {
            PaperMarioItemFood food = (PaperMarioItemFood) item;
            ItemStack stack = new ItemStack(food);
            System.out.println(stack.getDisplayName() + ": " + food.getHealAmount(stack) + " hunger, " + food.getSaturationModifier(stack) + " saturation");
        } else if (item instanceof ItemDrink) {
            ItemDrink drink = (ItemDrink) item;
            System.out.println(new ItemStack(drink).getDisplayName() + ": " + drink.getHealAmount() + " health");
        }
        GameRegistry.registerItem(item, name);
    }
}
