package io.github.mribby.papermario.item.crafting;

import cpw.mods.fml.common.registry.GameRegistry;
import io.github.mribby.papermario.Chef;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.RecipeSorter;

import static io.github.mribby.papermario.Chef.*;
import static io.github.mribby.papermario.item.PaperMarioItems.*;

public class Recipes {
    public static void registerRecipes() {
        RecipeSorter.register("papermario:mystery", RecipeMystery.class, RecipeSorter.Category.SHAPELESS, "after:minecraft:shapeless");
        RecipeSorter.register("papermario:mistake", RecipeMistake.class, RecipeSorter.Category.SHAPELESS, "after:minecraft:shapeless");
        RecipeSorter.register("papermario:spacefood", RecipeSpaceFood.class, RecipeSorter.Category.SHAPELESS, "after:minecraft:shapeless");
        GameRegistry.addRecipe(new RecipeMystery());
        GameRegistry.addRecipe(new RecipeMistake());
        /// PAPER MARIO ///
        addRecipe(TAYCE_T, apple_pie, apple, cake_mix);
        addRecipe(TAYCE_T, big_cookie, egg, cake_mix);
        addRecipe(TAYCE_T, big_cookie, goomnut, cake_mix);
        addRecipe(TAYCE_T, big_cookie, red_berry, cake_mix);
        addRecipe(TAYCE_T, big_cookie, yellow_berry, cake_mix);
        addRecipe(TAYCE_T, big_cookie, blue_berry, cake_mix);
        addRecipe(TAYCE_T, bland_meal, strange_leaf, goomnut);
        addRecipe(TAYCE_T, bland_meal, egg, mushroom);
        addRecipe(TAYCE_T, boiled_egg, egg, strange_leaf);
        addRecipe(TAYCE_T, boiled_egg, egg, stinky_herb);
        addRecipe(TAYCE_T, cake, cake_mix);
        addRecipe(TAYCE_T, coco_pop, coconut, cake_mix);
        addRecipe(TAYCE_T, deluxe_feast, whacka_bump, strange_leaf);
        addRecipe(TAYCE_T, deluxe_feast, potato_salad, shroom_steak);
        addRecipe(TAYCE_T, dizzy_dial, strange_leaf);
        addRecipe(TAYCE_T, dizzy_dial, strange_leaf, volt_shroom);
        addRecipe(TAYCE_T, dizzy_dial, strange_leaf, stinky_herb);
        addRecipe(TAYCE_T, egg_missile, fire_flower, egg);
        addRecipe(TAYCE_T, electro_pop, volt_shroom, cake_mix);
        addRecipe(TAYCE_T, fire_flower, dried_fruit, strange_leaf);
        addRecipe(TAYCE_T, fire_pop, cake_mix, fire_flower);
        addRecipe(TAYCE_T, fried_egg, egg);
        addRecipe(TAYCE_T, fried_shroom, mushroom);
        addRecipe(TAYCE_T, fried_shroom, super_shroom);
        addRecipe(TAYCE_T, frozen_fries, fire_flower, iced_potato);
        addRecipe(TAYCE_T, healthy_juice, special_shake, stinky_herb);
        addRecipe(TAYCE_T, healthy_juice, special_shake, dried_shroom);
        addRecipe(TAYCE_T, healthy_juice, special_shake, strange_leaf);
        addRecipe(TAYCE_T, honey_candy, cake_mix, honey_syrup);
        addRecipe(TAYCE_T, honey_shroom, mushroom, honey_syrup);
        addRecipe(TAYCE_T, honey_super, super_shroom, honey_syrup);
        addRecipe(TAYCE_T, honey_ultra, ultra_shroom, honey_syrup);
        addRecipe(TAYCE_T, hot_shroom, dried_shroom, super_shroom);
        addRecipe(TAYCE_T, hot_shroom, mushroom, super_shroom);
        addRecipe(TAYCE_T, hot_shroom, dried_shroom, volt_shroom);
        addRecipe(TAYCE_T, hot_shroom, mushroom, volt_shroom);
        addRecipe(TAYCE_T, hot_shroom, super_shroom, volt_shroom);
        addRecipe(TAYCE_T, hot_shroom, mushroom, fire_flower);
        addRecipe(TAYCE_T, hot_shroom, life_shroom);
        addRecipe(TAYCE_T, hot_shroom, volt_shroom);
        addRecipe(TAYCE_T, jelly_pop, cake_mix, jammin_jelly);
        addRecipe(TAYCE_T, jelly_shroom, mushroom, jammin_jelly);
        addRecipe(TAYCE_T, jelly_super, super_shroom, jammin_jelly);
        addRecipe(TAYCE_T, jelly_ultra, ultra_shroom, jammin_jelly);
        addRecipe(TAYCE_T, kooky_cookie, cake_mix, koopa_leaf);
        addRecipe(TAYCE_T, kooky_cookie, cake_mix, stinky_herb);
        addRecipe(TAYCE_T, kooky_cookie, cake_mix, maple_syrup);
        addRecipe(TAYCE_T, koopasta, koopa_leaf, dried_pasta);
        addRecipe(TAYCE_T, koopa_tea, koopa_leaf);
        addRecipe(TAYCE_T, lemon_candy, lemon, cake_mix);
        addRecipe(TAYCE_T, life_shroom, super_shroom, koopa_leaf);
        addRecipe(TAYCE_T, life_shroom, volt_shroom, koopa_leaf);
        addRecipe(TAYCE_T, life_shroom, ultra_shroom, koopa_leaf);
        addRecipe(TAYCE_T, life_shroom, life_shroom, koopa_leaf);
        addRecipe(TAYCE_T, life_shroom, super_shroom, goomnut);
        addRecipe(TAYCE_T, life_shroom, volt_shroom, goomnut);
        addRecipe(TAYCE_T, life_shroom, ultra_shroom, goomnut);
        addRecipe(TAYCE_T, life_shroom, life_shroom, goomnut);
        addRecipe(TAYCE_T, life_shroom, super_shroom, strange_leaf);
        addRecipe(TAYCE_T, life_shroom, ultra_shroom, strange_leaf);
        addRecipe(TAYCE_T, life_shroom, life_shroom, strange_leaf);
        addRecipe(TAYCE_T, lime_candy, lime, cake_mix);
        addRecipe(TAYCE_T, maple_shroom, mushroom, maple_syrup);
        addRecipe(TAYCE_T, maple_super, super_shroom, maple_syrup);
        addRecipe(TAYCE_T, maple_ultra, ultra_shroom, maple_syrup);
        addRecipe(TAYCE_T, nutty_cake, goomnut);
        addRecipe(TAYCE_T, potato_salad, iced_potato);
        addRecipe(TAYCE_T, shroom_cake, mushroom, cake_mix);
        addRecipe(TAYCE_T, shroom_steak, ultra_shroom);
        addRecipe(TAYCE_T, shroom_steak, life_shroom, mushroom);
        addRecipe(TAYCE_T, sleepy_sheep, red_berry, strange_leaf);
        addRecipe(TAYCE_T, sleepy_sheep, yellow_berry, strange_leaf);
        addRecipe(TAYCE_T, sleepy_sheep, blue_berry, strange_leaf);
        addRecipe(TAYCE_T, spaghetti, dried_pasta);
        addRecipe(TAYCE_T, special_shake, melon);
        addRecipe(TAYCE_T, special_shake, melon, apple);
        addRecipe(TAYCE_T, spicy_soup, fire_flower);
        addRecipe(TAYCE_T, strange_cake, strange_leaf, cake_mix);
        addRecipe(TAYCE_T, super_soda, honey_syrup);
        addRecipe(TAYCE_T, super_soda, maple_syrup);
        addRecipe(TAYCE_T, super_soda, apple);
        addRecipe(TAYCE_T, super_soda, blue_berry);
        addRecipe(TAYCE_T, super_soda, red_berry);
        addRecipe(TAYCE_T, super_soda, yellow_berry);
        addRecipe(TAYCE_T, super_soda, jammin_jelly);
        addRecipe(TAYCE_T, super_soda, honey_syrup, maple_syrup);
        addRecipe(TAYCE_T, super_soda, honey_syrup, koopa_leaf);
        addRecipe(TAYCE_T, super_soda, lime, maple_syrup);
        addRecipe(TAYCE_T, super_soda, lime, koopa_leaf);
        addRecipe(TAYCE_T, super_soda, lime, lemon);
        addRecipe(TAYCE_T, super_soda, lime, blue_berry);
        addRecipe(TAYCE_T, super_soda, lime, red_berry);
        addRecipe(TAYCE_T, super_soda, lime, yellow_berry);
        addRecipe(TAYCE_T, super_soda, lime, apple);
        addRecipe(TAYCE_T, super_soda, lemon, blue_berry);
        addRecipe(TAYCE_T, super_soda, lemon, red_berry);
        addRecipe(TAYCE_T, super_soda, lemon, yellow_berry);
        addRecipe(TAYCE_T, super_soda, lemon, maple_syrup);
        addRecipe(TAYCE_T, super_soda, lemon, koopa_leaf);
        addRecipe(TAYCE_T, super_soda, lemon, apple);
        addRecipe(TAYCE_T, super_soda, apple, blue_berry);
        addRecipe(TAYCE_T, super_soda, apple, red_berry);
        addRecipe(TAYCE_T, super_soda, apple, yellow_berry);
        addRecipe(TAYCE_T, super_soda, jammin_jelly, koopa_leaf);
        addRecipe(TAYCE_T, super_soda, yellow_berry, blue_berry);
        addRecipe(TAYCE_T, super_soda, yellow_berry, red_berry);
        addRecipe(TAYCE_T, super_soda, blue_berry, red_berry);
        addRecipe(TAYCE_T, super_soda, coconut, blue_berry);
        addRecipe(TAYCE_T, super_soda, coconut, red_berry);
        addRecipe(TAYCE_T, super_soda, coconut, yellow_berry);
        addRecipe(TAYCE_T, super_soda, coconut, apple);
        addRecipe(TAYCE_T, super_soda, coconut, melon);
        addRecipe(TAYCE_T, super_soda, coconut, koopa_leaf);
        addRecipe(TAYCE_T, sweet_shroom, cake_mix, ultra_shroom);
        addRecipe(TAYCE_T, sweet_shroom, cake_mix, life_shroom);
        addRecipe(TAYCE_T, tasty_tonic, red_berry, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, yellow_berry, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, blue_berry, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, apple, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, lemon, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, lime, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, coconut, honey_syrup);
        addRecipe(TAYCE_T, tasty_tonic, lime);
        addRecipe(TAYCE_T, tasty_tonic, lemon);
        addRecipe(TAYCE_T, tasty_tonic, bubble_berry);
        addRecipe(TAYCE_T, tasty_tonic, coconut);
        addRecipe(TAYCE_T, thunder_rage, dried_fruit, volt_shroom);
        addRecipe(TAYCE_T, volt_shroom, mushroom, koopa_leaf);
        addRecipe(TAYCE_T, volt_shroom, mushroom, goomnut);
        addRecipe(TAYCE_T, volt_shroom, mushroom, strange_leaf);
        addRecipe(TAYCE_T, volt_shroom, super_shroom, thunder_bolt);
        addRecipe(TAYCE_T, volt_shroom, ultra_shroom, thunder_bolt);
        addRecipe(TAYCE_T, volt_shroom, life_shroom, thunder_bolt);
        addRecipe(TAYCE_T, volt_shroom, mushroom, dried_fruit);
        addRecipe(TAYCE_T, volt_shroom, super_shroom, dried_fruit);
        addRecipe(TAYCE_T, volt_shroom, ultra_shroom, dried_fruit);
        addRecipe(TAYCE_T, volt_shroom, life_shroom, dried_fruit);
        addRecipe(TAYCE_T, yoshi_cookie, melon, cake_mix);
        addRecipe(TAYCE_T, yummy_meal, whacka_bump);
        addRecipe(TAYCE_T, yummy_meal, dried_fruit, dried_pasta);
        addRecipe(TAYCE_T, yummy_meal, dried_fruit, iced_potato);
        addRecipe(TAYCE_T, yummy_meal, iced_potato, strange_leaf);
        addRecipe(TAYCE_T, yummy_meal, potato_salad, hot_shroom);
        addRecipe(TAYCE_T, yummy_meal, potato_salad, spaghetti);
        addRecipe(TAYCE_T, yummy_meal, ultra_shroom, dried_pasta);
        addRecipe(TAYCE_T, yummy_meal, ultra_shroom, egg);
        addRecipe(TAYCE_T, yummy_meal, ultra_shroom, fire_flower);
        addRecipe(TAYCE_T, yummy_meal, ultra_shroom, iced_potato);
        /// PAPER MARIO: THE THOUSAND YEAR DOOR ///
        GameRegistry.addRecipe(new RecipeSpaceFood());
        addRecipe(ZESS_T, boos_sheet, point_swap, repel_cape);
        addRecipe(ZESS_T, choco_cake, cake_mix, inky_sauce);
        addRecipe(ZESS_T, choco_cake, mousse_cake, inky_sauce);
        addRecipe(ZESS_T, coco_candy, cake_mix, coconut);
        addRecipe(ZESS_T, coconut, dried_bouquet, coconut_bomb);
        addRecipe(ZESS_T, coconut_bomb, coconut, fire_flower);
        addRecipe(ZESS_T, couples_cake, snow_bunny, spicy_soup);
        addRecipe(ZESS_T, courage_meal, courage_shell, zess_deluxe);
        addRecipe(ZESS_T, courage_meal, courage_shell, zess_dinner);
        addRecipe(ZESS_T, courage_meal, courage_shell, zess_special);
        addRecipe(ZESS_T, courage_shell, point_swap, mr_softener);
        addRecipe(ZESS_T, courage_shell, dried_bouquet, courage_meal);
        addRecipe(ZESS_T, dried_shroom, life_shroom, mr_softener);
        addRecipe(ZESS_T, dried_shroom, mushroom, mr_softener);
        addRecipe(ZESS_T, dried_shroom, super_shroom, mr_softener);
        addRecipe(ZESS_T, dried_shroom, ultra_shroom, mr_softener);
        addRecipe(ZESS_T, earth_quake, point_swap, thunder_bolt);
        addRecipe(ZESS_T, egg_bomb, dried_bouquet, zess_dynamite);
        addRecipe(ZESS_T, egg_bomb, mystic_egg, fire_flower);
        addRecipe(ZESS_T, electro_pop, cake_mix, volt_shroom);
        addRecipe(ZESS_T, fire_flower, point_swap, ice_storm);
        addRecipe(ZESS_T, fire_pop, cake_mix, fire_flower);
        addRecipe(ZESS_T, fire_pop, cake_mix, hot_sauce);
        addRecipe(ZESS_T, fresh_juice, gradual_syrup);
        addRecipe(ZESS_T, fresh_juice, honey_syrup);
        addRecipe(ZESS_T, fresh_juice, jammin_jelly);
        addRecipe(ZESS_T, fresh_juice, keel_mango);
        addRecipe(ZESS_T, fresh_juice, maple_syrup);
        addRecipe(ZESS_T, fresh_juice, peachy_peach);
        addRecipe(ZESS_T, fresh_juice, gradual_syrup, koopa_leaf);
        addRecipe(ZESS_T, fresh_juice, honey_syrup, gradual_syrup);
        addRecipe(ZESS_T, fresh_juice, honey_syrup, jammin_jelly);
        addRecipe(ZESS_T, fresh_juice, honey_syrup, maple_syrup);
        addRecipe(ZESS_T, fresh_juice, honey_syrup, koopa_leaf);
        addRecipe(ZESS_T, fresh_juice, jammin_jelly, gradual_syrup);
        addRecipe(ZESS_T, fresh_juice, jammin_jelly, koopa_leaf);
        addRecipe(ZESS_T, fresh_juice, keel_mango, coconut);
        addRecipe(ZESS_T, fresh_juice, maple_syrup, gradual_syrup);
        addRecipe(ZESS_T, fresh_juice, maple_syrup, koopa_leaf);
        addRecipe(ZESS_T, fresh_juice, peachy_peach, coconut);
        addRecipe(ZESS_T, fresh_juice, koopa_leaf, coconut);
        addRecipe(ZESS_T, fried_egg, mystic_egg);
        addRecipe(ZESS_T, fruit_parfait, gradual_syrup, keel_mango);
        addRecipe(ZESS_T, fruit_parfait, honey_syrup, keel_mango);
        addRecipe(ZESS_T, fruit_parfait, honey_syrup, peachy_peach);
        addRecipe(ZESS_T, fruit_parfait, jammin_jelly, keel_mango);
        addRecipe(ZESS_T, fruit_parfait, jammin_jelly, peachy_peach);
        addRecipe(ZESS_T, fruit_parfait, keel_mango, peachy_peach);
        addRecipe(ZESS_T, fruit_parfait, maple_syrup, keel_mango);
        addRecipe(ZESS_T, fruit_parfait, maple_syrup, peachy_peach);
        addRecipe(ZESS_T, gold_bar, point_swap, gold_bar_x3);
        addRecipe(ZESS_T, healthy_salad, golden_leaf, koopa_leaf);
        addRecipe(ZESS_T, healthy_salad, koopa_leaf, horsetail);
        addRecipe(ZESS_T, heartful_cake, cake_mix, ruin_powder);
        addRecipe(ZESS_T, heartful_cake, peachy_peach, ruin_powder);
        addRecipe(ZESS_T, honey_candy, honey_syrup, cake_mix);
        addRecipe(ZESS_T, honey_shroom, honey_syrup, volt_shroom);
        addRecipe(ZESS_T, honey_shroom, mushroom, honey_syrup);
        addRecipe(ZESS_T, honey_shroom, honey_syrup, slow_shroom);
        addRecipe(ZESS_T, honey_super, life_shroom, honey_syrup);
        addRecipe(ZESS_T, honey_super, super_shroom, honey_syrup);
        addRecipe(ZESS_T, honey_syrup, point_swap, gradual_syrup);
        addRecipe(ZESS_T, honey_syrup, point_swap, mushroom);
        addRecipe(ZESS_T, honey_ultra, ultra_shroom, honey_syrup);
        addRecipe(ZESS_T, ice_storm, point_swap, fire_flower);
        addRecipe(ZESS_T, icicle_pop, honey_syrup, ice_storm);
        addRecipe(ZESS_T, ink_pasta, fresh_pasta, inky_sauce);
        addRecipe(ZESS_T, ink_pasta, inky_sauce, koopasta);
        addRecipe(ZESS_T, ink_pasta, inky_sauce, spaghetti);
        addRecipe(ZESS_T, ink_pasta, inky_sauce, spicy_pasta);
        addRecipe(ZESS_T, inky_sauce, hot_sauce, fresh_juice);
        addRecipe(ZESS_T, inky_sauce, hot_sauce, koopa_tea);
        addRecipe(ZESS_T, inky_sauce, hot_sauce, shroom_broth);
        addRecipe(ZESS_T, inky_sauce, hot_sauce, koopa_leaf);
        addRecipe(ZESS_T, inky_sauce, hot_sauce, zess_tea);
        addRecipe(ZESS_T, inky_sauce, hot_sauce, tasty_tonic);
        addRecipe(ZESS_T, jammin_jelly, point_swap, ultra_shroom);
        addRecipe(ZESS_T, jelly_candy, jammin_jelly, cake_mix);
        addRecipe(ZESS_T, jelly_shroom, jammin_jelly, volt_shroom);
        addRecipe(ZESS_T, jelly_shroom, mushroom, jammin_jelly);
        addRecipe(ZESS_T, jelly_super, life_shroom, jammin_jelly);
        addRecipe(ZESS_T, jelly_super, super_shroom, jammin_jelly);
        addRecipe(ZESS_T, jelly_ultra, ultra_shroom, jammin_jelly);
        addRecipe(ZESS_T, koopa_bun, keel_mango, koopa_leaf);
        addRecipe(ZESS_T, koopasta, fresh_pasta, koopa_leaf);
        addRecipe(ZESS_T, koopa_tea, koopa_leaf);
        addRecipe(ZESS_T, love_pudding, mystic_egg, mango_delight);
        addRecipe(ZESS_T, mango_delight, keel_mango, cake_mix);
        addRecipe(ZESS_T, maple_shroom, maple_syrup, volt_shroom);
        addRecipe(ZESS_T, maple_shroom, mushroom, maple_syrup);
        addRecipe(ZESS_T, maple_super, super_shroom, maple_syrup);
        addRecipe(ZESS_T, maple_syrup, super_shroom, point_swap);
        addRecipe(ZESS_T, maple_ultra, maple_syrup, ultra_shroom);
        addRecipe(ZESS_T, meteor_meal, fried_shroom, shooting_star);
        addRecipe(ZESS_T, meteor_meal, shroom_roast, shooting_star);
        addRecipe(ZESS_T, meteor_meal, shroom_steak, shooting_star);
        addRecipe(ZESS_T, mini_mr_mini, point_swap, power_punch);
        addRecipe(ZESS_T, mousse_cake, cake_mix);
        addRecipe(ZESS_T, mr_softener, point_swap, courage_shell);
        addRecipe(ZESS_T, mushroom, dried_shroom, hot_sauce);
        addRecipe(ZESS_T, mushroom, dried_shroom, peachy_peach);
        addRecipe(ZESS_T, mushroom, dried_shroom, power_punch);
        addRecipe(ZESS_T, mushroom, point_swap, honey_syrup);
        addRecipe(ZESS_T, mushroom, point_swap, dried_shroom);
        addRecipe(ZESS_T, mushroom, point_swap, poison_mushroom);
        addRecipe(ZESS_T, mushroom, point_swap, gold_bar);
        addRecipe(ZESS_T, omelette_meal, mystic_egg, horsetail);
        addRecipe(ZESS_T, omelette_meal, mystic_egg, mushroom);
        addRecipe(ZESS_T, omelette_meal, mystic_egg, super_shroom);
        addRecipe(ZESS_T, omelette_meal, mystic_egg, life_shroom);
        addRecipe(ZESS_T, omelette_meal, mystic_egg, ultra_shroom);
        addRecipe(ZESS_T, peach_tart, peachy_peach, cake_mix);
        addRecipe(ZESS_T, poison_mushroom, inky_sauce, slow_shroom);
        addRecipe(ZESS_T, power_punch, point_swap, mini_mr_mini);
        addRecipe(ZESS_T, repel_cape, point_swap, boos_sheet);
        addRecipe(ZESS_T, ruin_powder, point_swap, spite_pouch);
        addRecipe(ZESS_T, shooting_star, point_swap, thunder_rage);
        addRecipe(ZESS_T, shroom_broth, golden_leaf, poison_mushroom);
        addRecipe(ZESS_T, shroom_cake, mushroom, cake_mix);
        addRecipe(ZESS_T, shroom_cake, super_shroom, cake_mix);
        addRecipe(ZESS_T, shroom_cake, life_shroom, cake_mix);
        addRecipe(ZESS_T, mushroom_crepe, ultra_shroom, cake_mix);
        addRecipe(ZESS_T, fried_shroom, dried_shroom);
        addRecipe(ZESS_T, fried_shroom, mushroom);
        addRecipe(ZESS_T, fried_shroom, poison_mushroom);
        addRecipe(ZESS_T, fried_shroom, super_shroom);
        addRecipe(ZESS_T, fried_shroom, volt_shroom);
        addRecipe(ZESS_T, fried_shroom, dried_shroom, fire_flower);
        addRecipe(ZESS_T, fried_shroom, dried_shroom, volt_shroom);
        addRecipe(ZESS_T, fried_shroom, mushroom, dried_shroom);
        addRecipe(ZESS_T, fried_shroom, mushroom, koopa_leaf);
        addRecipe(ZESS_T, fried_shroom, mushroom, golden_leaf);
        addRecipe(ZESS_T, shroom_roast, slow_shroom);
        addRecipe(ZESS_T, shroom_roast, life_shroom);
        addRecipe(ZESS_T, shroom_roast, life_shroom, volt_shroom);
        addRecipe(ZESS_T, shroom_roast, mushroom, fire_flower);
        addRecipe(ZESS_T, shroom_roast, mushroom, super_shroom);
        addRecipe(ZESS_T, shroom_roast, mushroom, volt_shroom);
        addRecipe(ZESS_T, shroom_roast, mushroom, gradual_syrup);
        addRecipe(ZESS_T, shroom_roast, super_shroom, dried_shroom);
        addRecipe(ZESS_T, shroom_roast, super_shroom, volt_shroom);
        addRecipe(ZESS_T, shroom_roast, super_shroom, koopa_leaf);
        addRecipe(ZESS_T, shroom_roast, super_shroom, golden_leaf);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom);
        addRecipe(ZESS_T, shroom_steak, life_shroom, dried_shroom);
        addRecipe(ZESS_T, shroom_steak, life_shroom, mushroom);
        addRecipe(ZESS_T, shroom_steak, life_shroom, super_shroom);
        addRecipe(ZESS_T, shroom_steak, life_shroom, ultra_shroom);
        addRecipe(ZESS_T, shroom_steak, life_shroom, koopa_leaf);
        addRecipe(ZESS_T, shroom_steak, life_shroom, golden_leaf);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom, dried_shroom);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom, mushroom);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom, super_shroom);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom, volt_shroom);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom, koopa_leaf);
        addRecipe(ZESS_T, shroom_steak, ultra_shroom, golden_leaf);
        addRecipe(ZESS_T, sleepy_sheep, point_swap, tasty_tonic);
        addRecipe(ZESS_T, snow_bunny, ice_storm, golden_leaf);
        addRecipe(ZESS_T, spaghetti, fresh_pasta);
        addRecipe(ZESS_T, spicy_pasta, hot_sauce, fresh_pasta);
        addRecipe(ZESS_T, spicy_pasta, hot_sauce, spaghetti);
        addRecipe(ZESS_T, spicy_pasta, hot_sauce, koopasta);
        addRecipe(ZESS_T, spicy_soup, fire_flower);
        addRecipe(ZESS_T, spicy_soup, dried_bouquet);
        addRecipe(ZESS_T, spicy_soup, horsetail);
        addRecipe(ZESS_T, spicy_soup, snow_bunny);
        addRecipe(ZESS_T, spicy_soup, fire_flower, hot_sauce);
        addRecipe(ZESS_T, spicy_soup, fire_flower, dried_bouquet);
        addRecipe(ZESS_T, spite_pouch, point_swap, ruin_powder);
        addRecipe(ZESS_T, super_shroom, point_swap, maple_syrup);
        addRecipe(ZESS_T, super_shroom, point_swap, life_shroom);
        addRecipe(ZESS_T, super_shroom, point_swap, volt_shroom);
        addRecipe(ZESS_T, tasty_tonic, coconut);
        addRecipe(ZESS_T, tasty_tonic, hot_sauce);
        addRecipe(ZESS_T, tasty_tonic, hot_sauce, honey_syrup);
        addRecipe(ZESS_T, tasty_tonic, hot_sauce, peachy_peach);
        addRecipe(ZESS_T, tasty_tonic, hot_sauce, jammin_jelly);
        addRecipe(ZESS_T, tasty_tonic, hot_sauce, maple_syrup);
        addRecipe(ZESS_T, tasty_tonic, point_swap, sleepy_sheep);
        addRecipe(ZESS_T, thunder_bolt, point_swap, earth_quake);
        addRecipe(ZESS_T, thunder_rage, dried_bouquet, volt_shroom);
        addRecipe(ZESS_T, thunder_rage, point_swap, shooting_star);
        addRecipe(ZESS_T, trial_stew, poison_mushroom, couples_cake);
        addRecipe(ZESS_T, ultra_shroom, point_swap, jammin_jelly);
        addRecipe(ZESS_T, volt_shroom, thunder_bolt, life_shroom);
        addRecipe(ZESS_T, volt_shroom, thunder_bolt, mushroom);
        addRecipe(ZESS_T, volt_shroom, thunder_bolt, super_shroom);
        addRecipe(ZESS_T, volt_shroom, thunder_bolt, ultra_shroom);
        addRecipe(ZESS_T, volt_shroom, thunder_rage, life_shroom);
        addRecipe(ZESS_T, volt_shroom, thunder_rage, mushroom);
        addRecipe(ZESS_T, volt_shroom, thunder_rage, super_shroom);
        addRecipe(ZESS_T, volt_shroom, thunder_rage, ultra_shroom);
        addRecipe(ZESS_T, zess_cookie, cake_mix, maple_syrup);
        addRecipe(ZESS_T, zess_cookie, cake_mix, gradual_syrup);
        addRecipe(ZESS_T, zess_cookie, cake_mix, mystic_egg);
        addRecipe(ZESS_T, zess_deluxe, shroom_steak, healthy_salad);
        addRecipe(ZESS_T, zess_deluxe, ultra_shroom, fresh_pasta);
        addRecipe(ZESS_T, zess_dinner, mushroom, horsetail);
        addRecipe(ZESS_T, zess_dinner, super_shroom, fire_flower);
        addRecipe(ZESS_T, zess_dinner, super_shroom, horsetail);
        addRecipe(ZESS_T, zess_dinner, super_shroom, gradual_syrup);
        addRecipe(ZESS_T, zess_dinner, super_shroom, keel_mango);
        addRecipe(ZESS_T, zess_dinner, super_shroom, peachy_peach);
        addRecipe(ZESS_T, zess_dinner, ultra_shroom, keel_mango);
        addRecipe(ZESS_T, zess_dinner, life_shroom, fire_flower);
        addRecipe(ZESS_T, zess_dinner, life_shroom, gradual_syrup);
        addRecipe(ZESS_T, zess_dinner, life_shroom, horsetail);
        addRecipe(ZESS_T, zess_dinner, fresh_pasta, mystic_egg);
        addRecipe(ZESS_T, zess_dinner, fresh_pasta, coconut);
        addRecipe(ZESS_T, zess_dinner, fresh_pasta, healthy_salad);
        addRecipe(ZESS_T, zess_dinner, healthy_salad, fried_shroom);
        addRecipe(ZESS_T, zess_dinner, healthy_salad, koopasta);
        addRecipe(ZESS_T, zess_dinner, healthy_salad, spaghetti);
        addRecipe(ZESS_T, zess_dinner, spicy_pasta, coconut);
        addRecipe(ZESS_T, zess_dinner, meteor_meal, fruit_parfait);
        addRecipe(ZESS_T, zess_dynamite, egg_bomb, coconut_bomb);
        addRecipe(ZESS_T, zess_frappe, ice_storm, maple_syrup);
        addRecipe(ZESS_T, zess_frappe, ice_storm, jammin_jelly);
        addRecipe(ZESS_T, zess_special, mushroom);
        addRecipe(ZESS_T, zess_special, fresh_pasta);
        addRecipe(ZESS_T, zess_special, dried_shroom, fresh_pasta);
        addRecipe(ZESS_T, zess_special, ultra_shroom, fire_flower);
        addRecipe(ZESS_T, zess_special, ultra_shroom, peachy_peach);
        addRecipe(ZESS_T, zess_special, ultra_shroom, gradual_syrup);
        addRecipe(ZESS_T, zess_special, ultra_shroom, horsetail);
        addRecipe(ZESS_T, zess_special, super_shroom, fresh_pasta);
        addRecipe(ZESS_T, zess_special, life_shroom, fresh_pasta);
        addRecipe(ZESS_T, zess_special, healthy_salad, ink_pasta);
        addRecipe(ZESS_T, zess_special, healthy_salad, shroom_roast);
        addRecipe(ZESS_T, zess_special, healthy_salad, spicy_pasta);
        addRecipe(ZESS_T, zess_tea, golden_leaf);
        addRecipe(ZESS_T, zess_tea, maple_syrup, jammin_jelly);
        /// SUPER PAPER MARIO ///
        addRecipe(SAFFRON, block_meal, block_block);
        addRecipe(SAFFRON, dangerous_delight, poison_shroom);
        addRecipe(SAFFRON, dangerous_delight, ghost_shroom);
        addRecipe(SAFFRON, dayzee_syrup, dayzee_tear);
        addRecipe(SAFFRON, electro_pop, thunder_rage);
        addRecipe(SAFFRON, fried_egg, big_egg);
        addRecipe(SAFFRON, fried_shroom, shroom_shake);
        addRecipe(SAFFRON, golden_meal, gold_bar);
        addRecipe(SAFFRON, hamburger, power_steak);
        addRecipe(SAFFRON, healthy_salad, fresh_veggie);
        addRecipe(SAFFRON, herb_tea, smelly_herb);
        addRecipe(SAFFRON, honey_candy, honey_jar);
        addRecipe(SAFFRON, inky_soup, inky_sauce);
        addRecipe(SAFFRON, koopa_tea, koopa_leaf);
        addRecipe(SAFFRON, mango_juice, keel_mango);
        addRecipe(SAFFRON, megaton_dinner, pow_block);
        addRecipe(SAFFRON, meteor_meal, shooting_star);
        addRecipe(SAFFRON, peach_juice, peachy_peach);
        addRecipe(SAFFRON, roast_horsetail, horsetail);
        addRecipe(SAFFRON, roast_shroom_dish, super_shroom_shake);
        addRecipe(SAFFRON, roast_whacka_bump, whacka_bump);
        addRecipe(SAFFRON, sap_syrup, sap_soup);
        addRecipe(SAFFRON, shroom_steak, ultra_shroom_shake);
        addRecipe(SAFFRON, sky_juice, blue_apple);
        addRecipe(SAFFRON, sky_juice, pink_apple);
        addRecipe(SAFFRON, sky_juice, red_apple);
        addRecipe(SAFFRON, sky_juice, yellow_apple);
        addRecipe(SAFFRON, slimy_extract, slimy_shroom);
        addRecipe(SAFFRON, snow_cone, ice_storm);
        addRecipe(SAFFRON, spaghetti_plate, fresh_pasta_bunch);
        addRecipe(SAFFRON, spicy_soup, fire_burst);
        addRecipe(SAFFRON, spit_roast, bonein_cut);
        addRecipe(SAFFRON, sweet_cookie_snack, cake_mix);
        addRecipe(SAFFRON, town_special, primordial_fruit);
        addRecipe(SAFFRON, warm_cocoa, mild_cocoa_bean);
        addRecipe(DYLLIS, awesome_snack, fresh_veggie, cake_mix);
        addRecipe(DYLLIS, berry_snow_bunny, snow_bunny, pink_apple);
        addRecipe(DYLLIS, chocolate_cake, mild_cocoa_bean, cake_mix);
        addRecipe(DYLLIS, choco_pasta_dish, mild_cocoa_bean, fresh_pasta_bunch);
        addRecipe(DYLLIS, couples_cake, snow_bunny, berry_snow_bunny);
        addRecipe(DYLLIS, dyllis_breakfast, shroom_shake, spicy_soup);
        addRecipe(DYLLIS, dyllis_deluxe, shroom_steak, gorgeous_steak);
        addRecipe(DYLLIS, dyllis_dinner, fried_shroom, meat_pasta_dish);
        addRecipe(DYLLIS, dyllis_dynamite, egg_bomb, dyllis_breakfast);
        addRecipe(DYLLIS, dyllis_lunch, fried_shroom, spaghetti_plate);
        addRecipe(DYLLIS, dyllis_special, roast_shroom_dish, fruity_hamburger);
        addRecipe(DYLLIS, egg_bomb, big_egg, fire_burst);
        addRecipe(DYLLIS, emergency_ration, fire_burst, shroom_shake);
        addRecipe(DYLLIS, fruit_parfait, peachy_peach, snow_cone);
        addRecipe(DYLLIS, fruity_cake, peachy_peach, mushroom_crepe);
        addRecipe(DYLLIS, fruity_hamburger, power_steak, keel_mango);
        addRecipe(DYLLIS, fruity_punch, keel_mango, peachy_peach);
        addRecipe(DYLLIS, fruity_shroom, peachy_peach, shroom_shake);
        addRecipe(DYLLIS, gingerbread_house, chocolate_cake, mousse);
        addRecipe(DYLLIS, golden_chocobar, mild_cocoa_bean, golden_leaf);
        addRecipe(DYLLIS, gorgeous_steak, power_steak, hamburger);
        addRecipe(DYLLIS, gradual_syrup, longlast_shake, peachy_peach);
        addRecipe(DYLLIS, heartful_cake, cake_mix, lovely_chocolate);
        addRecipe(DYLLIS, heavy_meal, honey_jar, honey_candy);
        addRecipe(DYLLIS, honey_shroom, shroom_shake, honey_jar);
        addRecipe(DYLLIS, honey_super, super_shroom_shake, honey_jar);
        addRecipe(DYLLIS, horsetail_tart, horsetail, cake_mix);
        addRecipe(DYLLIS, hot_dog, power_steak, fresh_veggie);
        addRecipe(DYLLIS, ink_pasta, fresh_pasta_bunch, inky_sauce);
        addRecipe(DYLLIS, koopa_dumpling, cake_mix, koopa_leaf);
        addRecipe(DYLLIS, koopa_pilaf, koopa_leaf, horsetail);
        addRecipe(DYLLIS, koopasta, fresh_pasta_bunch, koopa_leaf);
        addRecipe(DYLLIS, love_pudding, lovely_chocolate, big_egg);
        addRecipe(DYLLIS, love_noodle_dish, lovely_chocolate, fresh_pasta_bunch);
        addRecipe(DYLLIS, lovely_chocolate, mild_cocoa_bean, fire_burst);
        addRecipe(DYLLIS, luxurious_set, dyllis_dinner, fried_shroom);
        addRecipe(DYLLIS, mango_pudding, keel_mango, big_egg);
        addRecipe(DYLLIS, meat_pasta_dish, fresh_pasta_bunch, power_steak);
        addRecipe(DYLLIS, mixed_shake, peach_juice, mango_juice);
        addRecipe(DYLLIS, mousse, cake_mix, big_egg);
        addRecipe(DYLLIS, mushroom_crepe, shroom_shake, cake_mix);
        addRecipe(DYLLIS, odd_dinner, poison_shroom, fried_shroom);
        addRecipe(DYLLIS, omelette_plate, big_egg, horsetail);
        addRecipe(DYLLIS, peach_tart, peachy_peach, cake_mix);
        addRecipe(DYLLIS, primordial_dinner, primordial_fruit, shroom_shake);
        addRecipe(DYLLIS, sap_muffin, sap_soup, cake_mix);
        addRecipe(DYLLIS, shroom_broth, smelly_herb, shroom_shake);
        addRecipe(DYLLIS, shroom_cake, super_shroom_shake, cake_mix);
        addRecipe(DYLLIS, shroom_chocobar, mild_cocoa_bean, shroom_shake);
        addRecipe(DYLLIS, shroom_delicacy, shroom_shake, dayzee_tear);
        addRecipe(DYLLIS, shroom_pudding, big_egg, shroom_shake);
        addRecipe(DYLLIS, snow_bunny, koopa_leaf, ice_storm);
        addRecipe(DYLLIS, space_food, ice_storm, shroom_shake);
        addRecipe(DYLLIS, spicy_dinner, big_egg, hot_sauce);
        addRecipe(DYLLIS, spicy_pasta_dish, hot_sauce, fresh_pasta_bunch);
        addRecipe(DYLLIS, stamina_juice, inky_sauce, honey_jar);
        addRecipe(DYLLIS, standard_chocolate, mild_cocoa_bean, poison_shroom);
        addRecipe(DYLLIS, sweet_chocobar, mild_cocoa_bean, honey_jar);
        addRecipe(DYLLIS, trial_stew, couples_cake, poison_shroom);
        addRecipe(DYLLIS, veggie_set, healthy_salad, big_egg);
        addRecipe(DYLLIS, volcano_shroom, hot_sauce, shroom_shake);
        addRecipe(DYLLIS, weird_extract, peach_juice, hot_sauce);
    }

    private static void addRecipe(Chef chef, Item output, Object... params) {
        addRecipe(chef, new ItemStack(output), params);
    }

    private static void addRecipe(Chef chef, ItemStack output, Object... params) {
        GameRegistry.addShapelessRecipe(output, params);
        chef.addRecipe(output);
    }
}
